global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js 백엔드 모니터링
  - job_name: 'viba-backend'
    static_configs:
      - targets: ['backend:5001']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Python AI 서비스 모니터링
  - job_name: 'viba-ai-service'
    static_configs:
      - targets: ['ai-service:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL 모니터링 (postgres_exporter 사용 시)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis 모니터링 (redis_exporter 사용 시)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

# 알람 규칙 (선택사항)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093